### ISSUE TITLE
Use attribute for class instead interface

### ISSUE THREAD

**Issue by h-ebrahimi** [TanvirArjel/TanvirArjel.Extensions.Microsoft.DependencyInjection#2]
hi

Use **attributes** in the **class** instead of **interfaces**
We can also get the list of assemblies from the **project path** and reach our goal by receiving the types that have these attributes.
I wrote these and I can send you my code.
thanks

**Comment by TanvirArjel** [comment]
@h-ebrahimi There is already attribute support.
