### ISSUE TITLE
Add support for IHostedService

### ISSUE THREAD

**Issue by alienwareone** [TanvirArjel/TanvirArjel.Extensions.Microsoft.DependencyInjection#5]
Like this package!

Would love to see a new attribute:
**[HostedService]**

https://github.com/aspnet/Hosting/blob/master/src/Microsoft.Extensions.Hosting.Abstractions/ServiceCollectionHostedServiceExtensions.cs

**Comment by TanvirArjel** [comment]
@alienwareone  Thank you so much for your feature request. We are thinking about this and an update will be shared here.

**Comment by alienwareone** [comment]
Sorry outdated link. It's now Singleton.

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/ServiceCollectionHostedServiceExtensions.cs

**Comment by TanvirArjel** [comment]
@alienwareone Please update to version `1.3.0`. Your requested feature has been added.
