### ISSUE TITLE
Reverse registering mechanism

### ISSUE THREAD

**Issue by erhan355** [TanvirArjel/TanvirArjel.Extensions.Microsoft.DependencyInjection#7]
I had a look of your library,it is helpful but it seems to me attributes should be applied on concrete classes.Interface is just a blueprint of a class and can be implemented by multiple classes.What happens If two classes implement same interface but with different lifetime ?

**Comment by TanvirArjel** [comment]
"What happens If two classes implement the same interface but with different lifetime ?"

Then you have to use the factory to get the desired implementation.
