### ISSUE TITLE
Config Priority in Startup.cs

### ISSUE THREAD

**Issue by PooyaKeshvari** [TanvirArjel/TanvirArjel.Extensions.Microsoft.DependencyInjection#8]
hi   , when we have two Implemented class from an Interface , How can we control which one can be Run for us? ?  plz show me how can i config that in startup.cs ?       services.AddServicesWithAttributeOfType<HostedServiceAttribute>();  Has Error.

For example , i have InterfaceTest and Two class that implemented it , in InterfaceTest i have a TestMethod() , in BaseClass1 TestMethod do something , and in BaseClass2  Do Something Else ,  If I Use InterfaceTest.TestMethod on Controller , I have Which One ?

**Comment by TanvirArjel** [comment]
You can use the [IgnoreServiceRegistration] attribute to suppress one implementation.
